### ISSUE TITLE
Backend cleanup

### ISSUE THREAD

**Issue by DominikRuf** [ToKoSoftware/dhbw-svm-portal#130]
- [x] FindOne mit FindByPK
- [x] Nur aktuelles(nicht abgelaufenes) anzeigen
- [x] Validierungen (datum, etc)
- [x] create membership fixen
- [x] delete poll fixen
- [x] Create Team überprüfen, ob die maintain rolle existiert (und überhaupt current org ist?) -> generell bitte überprüfen, ob nicht irgendwelche ids einfach irgendwo reingeschrieben werden in relationships
- [x] Read Team: Als admin darf ich alle teams sehen, auch wenn ich nicht Mitglied bin, das selbe wenn ich die Maintain role habe, muss ich nicht member des teams sein um diese zu sehen bzw bearbeiten
- [x] Update user geht nicht `(node:88) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Object.updateUser (/home/node/app/server/src/api/v1/users/update-user.ts:28:49)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:88) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 38) `

- [x] Admins dürfen access_code sehen
- [x] Events öffentlich machen
- [x] delete team fixen (findOne auf polls statt findAll)
- [x] Default scopes anpassen (Sortierung bei Events, Polls, ...), Roles und Teams alphabetisch
- [x] Scope is null bei organizations get all
- [x] Überprüfen, ob doppelte memberships/role assignments vergeben werden können (einfach findOrCreate verwenden)
- [x] checks in create und update redduzieren. Felder die nicht geändert werden dürfen einfach .delete.

**Comment by DominikRuf** [comment]
- [ ] create membership fixen
- [ ] delete poll fixen
